lab-4
tatia2501/is-web-y24 pull request #5
Opened 2022-11-13 22:23 UTC by tatia2501

2022-11-14 11:38 UTC, BakasaRus requested changes

2022-11-14 11:38 UTC, BakasaRus commented on Scripts/LoadTime.js
> +})();
Какие-то магические скобочки

2022-11-14 11:38 UTC, BakasaRus commented on Scripts/ActiveState.js
> +                el[i].className += ' current';
Лучше править через `classList`

2022-11-14 11:38 UTC, BakasaRus commented on Scripts/ActiveState.js
> +        var url=document.location.href;
Что за `var` и чем он отличается от `let` и `const`?

2022-11-28 12:41 UTC, tatia2501 commented on Scripts/ActiveState.js
> +        var url=document.location.href;
Var:
- var, созданная вне функции, действует как глобальная переменная, если внутри функции - локальная
- отсутствие блочной области видимости
- повторное объявление
- поднятие переменной (все переменные var считаются объявленными перед запуском скрипта. При этом они остаются undefined до тех пор, пока не выполнится код инициализации)
Let:
- переменные нельзя объявить повторно
- переменные тоже всплывают, но при попытке обратиться к ним до инициализации будет ошибка
- переменные имеют блочную область видимости
Const - константы
- попытка изменить значение константы приведёт к ошибке
- область видимости как у let

2022-11-28 12:45 UTC, tatia2501 commented on Scripts/LoadTime.js
> +})();
Последние скобочки запускают выполнение функции сразу после ее определения

2022-12-12 14:00 UTC, merged