lab-6
tatia2501/is-web-y24 pull request #7
Opened 2022-12-12 11:01 UTC by tatia2501

2022-12-12 12:32 UTC, BakasaRus requested changes
Посмотри, какие ещё есть способы получить данные из интернетов, кроме `fetch()`

2022-12-12 12:32 UTC, BakasaRus commented on Scripts/Account.js
> +    container.innerHTML = '<iframe src="https://gifer.com/embed/L6MI" width=200 height=200></iframe>';
Кажется, лучше скачать котика и разместить в проекте сам файл, а не использовать фрейм

2022-12-12 13:47 UTC, tatia2501 commented on Scripts/Account.js
> +    container.innerHTML = '<iframe src="https://gifer.com/embed/L6MI" width=200 height=200></iframe>';
способы выполнения HTTP-запросов:
XMLHttpRequest - можно использовать для запроса данных от веб-сервера;
JQuery.ajax - до недавнего времени широко используемая библиотека для выполнения HTTP-запросов, все методы  возвращают расширенный набор объекта XMLHTTPRequest;
Qwest - простая библиотека ajax, основанная на промисах, поддерживающая уникальные данные XmlHttpRequest2;
SuperAgent - ajax API, созданный для гибкости и читаемости, с низкой кривой обучения, также работает с Node.js;
Axios - основанная на промисах HTTP-библиотека для выполнения HTTP-запросов и в браузере, и в Node.js

2022-12-19 15:16 UTC, BakasaRus approved these changes

2022-12-20 09:34 UTC, merged